version: 2

docker_sbt: &docker_sbt
  docker:
    - image: circleci/openjdk:8-jdk
      environment:
        DEBIAN_FRONTEND: noninteractive
        SBT_OPTS: -Xms256m -Xmx756G -XX:+CMSClassUnloadingEnabled -XX:+UseSerialGC -XX:MaxMetaspaceSize=2G
        DISABLE_SCALAFMT: true
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m

determine_subproject: &determine_subproject
  run:
    command: |
      version=`git describe --always | grep -Po '[0-9\.-]+'`
      project=`git describe --always | grep -Po '^\S+(?=/)'`
      echo "export VERSION=${version}" >> $BASH_ENV
      echo "export PROJECT=${project}" >> $BASH_ENV

cache_save: &cache_save
  save_cache:
    paths:
      - ~/.m2
      - ~/.sbt
      - ~/.ivy2/cache
    key: v1-{{ checksum "build.sbt" }}

cache_restore: &cache_restore
  restore_cache:
    keys:
      - v1-{{ checksum "build.sbt" }}
      - v1-
jobs:

  release:
    <<: *docker_sbt
    steps:
      - checkout
      - *cache_restore
      - *determine_subproject
      - run:
          name: Release
          command: sbt ';project '${PROJECT}' ;set version := "'${VERSION}'"; test; publish'
      - *cache_save

  test:
    <<: *docker_sbt
    steps:
      - checkout
      - *cache_restore
      - run:
          name: Test all subprojects
          command: sbt test
      - *cache_save

  master-build:
    jobs:
      - release:
          filters: {tags: {only: /\S+\/([0-9\.-]+)/}}

  pr-build:
    jobs:
      - test:
          filters: {branches: {ignore: master}}

